# -*- coding: utf-8 -*-
"""SunSense System-ENG207 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0WVHStOo94mcqMXOH7dw4dBqTbY_NTE
"""

# SunSense  RS Solar Monitoring System
#ENG207 - Project (Shahed & Retaj)
# Summer 2025/2026
# Dr. Rashed Ahmed
#Description :
# This program monitors solar panel voltage and power under Kuwait's weather conditions.
# It enables users to generate or load data , analyze readings , and identify normal , warning,
# and the critical states . The program helps evaluate how the environmental factors such as temperature and
# humidty impact solar panel performance and efficiency .





#import required libraries
import random  # import random used to generate random voltage values
import math # import math  module used for mathematical calculations
import matplotlib.pyplot as plt # import matplotlib used to create graphs


CURRENT= 10 # the current for Sunsense system = 10A fixed value

#The first function
#Function to display the main menu of SunSense RS system
# It shows all options for the user
def display_menu():
  print("====================================")
  print(" Welcome To SunSense RS Solar Panel System,please select an option:")
  print("====================================")
  print("1.Generate Solar sensors Data")
  print("2.Set Threshold Levels")
  print("3.View Raw Data")
  print("4.Calculate Stat")
  print("5. Threshold Monitoring")
  print("6.Compare Scenarios")
  print("7.Plot Results")
  print("8.Exit")

#**********************

#The second function
# Function to generate solar sensor data
def generate_data():
  voltage_data = []  # list to store voltage readings :)
  power_data = [] # list to store power readings :)
 # user can choose either to create random data or reading from file
  print( "Choose data source")
  print("G.Random Data")
  print("L. csv File")

# An imprtant note : in Jupyter notebook , read_data() was used to read values from a csv file
#here if-elif-else statements are used inside generate_data ()
# to allow the user to choose between  generating random data or reading data from a CSV file.
  choice = input("Enter your choice (G-L): ")

  #  choice one : Random data generation
  if choice == "G":
    n = int(input("Enter number of reading : "))
    for i in range(n):
      voltage = random.randint(10, 22)  # generate voltage between 10v and 22v
      power = voltage * CURRENT # Power for Sunsense system is calculated using this formula

       # the values are stored in lists
      voltage_data.append(voltage)
      power_data.append(power)

  # Choice two :reading from CSV (Reading data from file)
  # Run the cell below to create the CSV file
  #then its can be use as an input data source.
  elif choice == "L":
    file = open("data.csv", "r")

    for line in file:
      value = (line.strip())

      if value == "" or value == "Voltage":
        continue
      voltage = int(value) # Convert to integer
      power = voltage * CURRENT
      voltage_data.append(voltage)
      power_data.append(power)

    file.close()
  else:
    print("Invalid choice. Please try again.")

  return voltage_data, power_data # Return the generated data



# **********************


#The Third Function
# This function to display generated voltage and power in clear format :)
def View_data(voltage_data, power_data):
  if not voltage_data:
    print("No data available! Please create data first") # user must creat data at first
  else:
    for i in range(len(voltage_data)):
      print(f"Reading {i+1} : Voltage = {voltage_data[i]}V, Power = {power_data[i]}W")


#*********************



# The fourth function
# This function analysis voltage data and caluclates min,max, average& std_dev
def calculate_statistics (voltage_data):

  # Check if data exists
  if len(voltage_data) == 0:
    print("No data available! Please create data first")
    return
    #min and max values
  min_Voltage = voltage_data[0]
  max_Voltage = voltage_data[0]
  total_Voltage = 0
  # average value
  for v in voltage_data:
    if v < min_Voltage:
      min_Voltage = v
    if v > max_Voltage:
      max_Voltage = v
    total_Voltage += v
  average_Voltage = total_Voltage / len(voltage_data)
   # calculate variance
  variance_Voltage = 0
  for v in voltage_data:
    variance_Voltage += (v - average_Voltage) ** 2
  variance_Voltage /= len(voltage_data)
   # standard deviation
  std_dev = math.sqrt(variance_Voltage)
  # print results
  print("Statistics: ")
  print(f"Minimum Voltage: {min_Voltage}V")
  print(f"Maximum Voltage: {max_Voltage}V")
  print(f"Average_Voltage: {average_Voltage:.2f}")
  print(f"Standard Deviation: {std_dev:.2f}")



#********************




# The fifth funnction
# Tuple ranges for voltage thresholds

NORMAL_RANGE = (15, 22)
WARNING_RANGE = (10, 15)

# function to check voltage levels and classify them as Normal , Waringing or Critcal
def threshold_monitoring(voltage_data):

  #check if there is no data
  if not voltage_data:
    print("No data available! Please create data first")
  else:
    warning_count = 0
    critical_count = 0

  # loop through all voltage readings
    for i in range(len(voltage_data)):
      voltage = voltage_data[i]

      # Check voltage level and assign status
      if NORMAL_RANGE[0] <= voltage <= NORMAL_RANGE[1]:
        status = "Normal"
      elif WARNING_RANGE[0] <= voltage <= NORMAL_RANGE[1]: # Corrected upper bound from WARNING_RANGE[1] to NORMAL_RANGE[1]
        status = "Warning"
        warning_count += 1

      else:
        status = "Critical"
        critical_count += 1

        # Print each reading with it status :
        print("Reading " ,i + 1 , ": Voltage = ", voltage, "V :",status)

    # Print total counts of warings ana critical counts
    print("Number of Warning Readings:", warning_count)
    print("Number of Critical Readings:", critical_count)

    #*********************


# The sixth function
# Function to compare Solar Panel performance under diffrent weather condotions.

def compare_scenarios():

  normal = [] # Corrected variable name from normal_count

  humid = []

  fault = []

  for i in range(5):
    normal.append(random.randint(15,22)) # Normal
    humid.append(random.randint(10,15))  # warning

    if i % 2 == 0:
      fault.append(random.randint(0,9)) # below 10
    else :
      fault.append(random.randint(23,30)) # above 22

  normal_avg = sum(normal)/len(normal)
  humid_avg = sum(humid)/len(humid)
  fault_avg = sum(fault)/len(fault)

  print("--- Scenario Comparison ---")
  print("Normal Average :", normal_avg)
  print("Humidity Average :", humid_avg)
  print("Fault Average :", fault_avg)


#***************


# The sevnth function
# Function to display predefined voltage threshold levels

def display_thresholds():
  print("\n--- Threshold Levels ---")
  print("Normal: 15V - 22V")
  print("Waring: 10V - 15V")
  print("Critical: Below 10V or Above 22V")


# The eighth function
# Function to plot voltage readings using yellow & blue
def plot_data(voltage_data):

  if not voltage_data:
    print("No data available . Please generate data")
  else:
    x =list(range(len(voltage_data))) #create x-axis values (reading numbers)
    plt.scatter(x, voltage_data, color='blue') # plot data points as blue dots
    plt.plot(x, voltage_data, color='yellow') # plot line connecting the pints in yellow
    plt.xlabel('Reading Number') # label x-axis
    plt.ylabel('Voltage (V)') # label y-axis
    plt.title('Voltage Readings') # add title to the graph

    plt.show()




   #****************


# The Main Function that controls the program flow and user interaction
def main():
  voltage_data = []
  power_data = []
  while True:
    display_menu()
    choice = input("Enter your choice (1-8): ")
    if choice == "1":
      voltage_data, power_data = generate_data()
      print("Data generated successfully!")
    elif choice =="2":
     display_thresholds()

    elif choice == "3":
     View_data(voltage_data, power_data)
     print("Data viewed , successfully!")

    elif choice == "4":
      calculate_statistics(voltage_data)
      print("Statistics calculated successfully!")

    elif choice == "5":
      threshold_monitoring(voltage_data)
      print("Threshold Monitoring completed")

    elif choice == "6":
      compare_scenarios()

    elif choice == "7":
      plot_data(voltage_data)

    elif choice == "8" :
      print("Exiting the program , Goodbye!")
      break
    else:
      print("Invalid choice. Please try again.")

# call main
main()

file = open("data.csv", "w")
file.write("Voltage\n")
file.write("18\n")
file.write("20\n")
file.write("14\n")
file.write("22\n")
file.write("10\n")
file.close()